config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :people
  get '/', to: "site#home"

  resources :projects, only: [:index, :show, :new, :create] do
    resources :time_entries, except: [:show]
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participation.rb
class Participation < ApplicationRecord
	belongs_to :person
	belongs_to :project
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :participations
	has_many :projects, through: :participations
end

app/models/project.rb
class Project < ApplicationRecord
  has_attached_file :logo, styles: {:medium=> "300x300>", :thumb => "100x100>"}
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\z/

  has_many :time_entries
  validates :name, :description, presence: true

  has_many :entries
  has_many :participations
  has_many :people, through: :participations
  
  class << self
    def clean_old
      projects = where('created_at < ?', last_week)
      projects.destroy_all
    end

    def get_first_created(limit)
      order(created_at: :asc).limit(limit)
    end

    private

    def last_week
      Date.today - 1.week 
    end
  end
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :project

  validates :minutes, presence: true

  class << self
    def last_month
      where('date > ?', Date.today - 1.month)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	def new
		@person = Person.new
		render "new"
	end

	def create
		@person = Person.new(
			:name => params[:person][:name],
			:age => params[:person][:age],
			
			)

		@person.save
		
		redirect_to ()
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.get_first_created(10)
    render 'index'
  end

  def show
    @project = Project.find_by(id: params[:id])
    if @project.present?
      render :show
    else
      render file: 'public/404.html'
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to "/projects/#{@project.id}"
    else
      flash[:error] = @project.errors.message
      render 'new'
    end
  end

  def project_params
    params.require(:project).permit(:name, :description, :logo)
  end



end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    render 'home'
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  def index
    @time_entries = project.time_entries.last_month
  end

  def new
    @time_entry = project.time_entries.new
  end

  def create
    @time_entry = project.time_entries.new(time_entry_params)
    if @time_entry.save
      redirect_to "/projects/#{project.id}/time_entries"
    else
      flash[:alert] = @time_entry.errors.full_messages
      render 'new'
    end
  end

  def edit
    time_entry
  end

  def update
    if time_entry.update(time_entry_params)
      redirect_to "/projects/#{project.id}/time_entries"
    else
      render 'edit'
    end
  end

  def destroy
    time_entry.destroy
    redirect_to "/projects/#{project.id}/time_entries"
  end

  private

  def project
    @project = Project.find_by(id: params[:project_id])
  end

  def time_entry
    @time_entry = project.time_entries.find_by(id: params[:id])
  end

  def time_entry_params
    params.require(:time_entry).permit(:hours, :minutes, :date, :comments)
  end







end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        WelcomeMailer.welcome_email(@user).deliver_now
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auctionsite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/new.html.erb
<h1>Add person</h1>
<%= form_for @person do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :age %>
	<%= select(@person, :age, (1..99).to_a) %>
<%= f.button %>
<% end %>

app/views/projects/index.html.erb
<h1>Index Projects</h1>
<ul>
  <% @projects.each do |project| %>
    <li>
      <%= project.name %> 
      <% if project.description.present? %>
        - <%= project.description %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1> Add a new proyect </h1>
<%= flash[:error] %>
<%= form_for @project,:html=>{:multipart=>true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :logo %>
  <%= f.file_field :logo %>

  <%= f.button %>
<% end %>

app/views/projects/show.html.erb
<h1> Name: <%= @project.name %></h1>
<p> Description: <%= @project.description %></p>
<%= image_tag@project.logo.url %>

app/views/site/home.html.erb
HOLAAAA!

app/views/time_entries/_form.html.erb
<%= form_for [@project, @time_entry] do |f| %>
  <%= f.label :hours %>
  <%= f.text_field :hours %>

  <%= f.label :minutes %>
  <%= f.text_field :minutes %>

  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :comments %>
  <%= f.text_field :comments %>

  <%= f.submit 'Save' %> 
  <%= link_to 'Cancel', project_time_entries_path(@project) %> 
<% end %>

app/views/time_entries/edit.html.erb
<h1> Update time entry to <%= @project.name %></h1>
<%= render 'form' %>

app/views/time_entries/index.html.erb
<h1> <%= @project.name %></h1>

<ul>
  <% @time_entries.each do |entry| %>
    <li>
      <%= entry.hours %> h
      <%= entry.minutes %> m -
      <%= entry.date %>
      <%= link_to 'Edit', edit_project_time_entry_path(@project, entry)%>
      <%= link_to('Delete', project_time_entry_path(@project, entry),
        method: :delete, data: { confirm: "Are you sure?" }) %>
    </li>
  <% end %>
</ul>  

app/views/time_entries/new.html.erb
<h1> New time entry to <%= @project.name %></h1>
<% if flash[:alert] %>
  <%=  flash[:alert] %>
<% end %>
<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>